### PR TITLE
refactor: use "picocolors" instead of "chalk"

### PR DESCRIPTION
**Pull request by Lete114**

### CODE REVIEW

**Comment by YunYouJun** [comment]
Thanks for your contribution.

I checked out picocolors README, its advantage is with smaller and faster, right?
Before we merge it, I'd like to ask if its API is nearly the same as chalk's.
Are there any other examples of large projects using picocolors?

**Comment by Lete114** [comment]
I know of hexo, postcss is using picocolors

**Comment by Lete114** [comment]
As for the use of api, I think it should be able to meet the current nnrm

**Review by YunYouJun — APPROVED** [review]

**Comment by YunYouJun** [comment]
Released in `v0.3.8`.

**Pull request merged**
